# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: QuinnSupplee.com
email: quinn@quinnsupplee.com
description: > # this means to ignore newlines until "baseurl:"
 Personal web site of Quinn Supplee.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.quinnsupplee.com" # the base hostname & protocol for your site
twitter_username: quinns
github_username:  quinns

# Build settings
markdown: kramdown

# SASS settings
sass:
    sass_dir: _sass
    style: compressed


paginate: 10
paginate_path: "/posts/page:num/"
gems: [jekyll-paginate]
  - jekyll-redirect-from

excerpt_separator: <!--more-->



